import os
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import ListFlowable, ListItem, Paragraph, SimpleDocTemplate, Spacer


class DossierService:
    """Service class for compiling forensic evidence PDF report documents."""

    @staticmethod
    async def generate_pdf_report(target_handle: str, findings: list[str]) -> str:
        """Asynchronously compiles a professional PDF dossier for a target entity.

        Creates the output/ directory if it doesn't exist, saves the PDF, and returns the file path.
        """
        output_dir = os.path.join(os.getcwd(), "output")
        os.makedirs(output_dir, exist_ok=True)

        safe_handle = "".join(c if c.isalnum() or c in ("-", "_") else "_" for c in target_handle)
        timestamp_str = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        filename = f"dossier_{safe_handle}_{timestamp_str}.pdf"
        file_path = os.path.join(output_dir, filename)

        doc = SimpleDocTemplate(
            file_path,
            pagesize=letter,
            rightMargin=54,
            leftMargin=54,
            topMargin=54,
            bottomMargin=54,
        )

        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "DossierTitle",
            parent=styles["Title"],
            fontSize=22,
            leading=26,
            textColor=colors.HexColor("#1A202C"),
            alignment=0,
            spaceAfter=12,
        )
        subtitle_style = ParagraphStyle(
            "DossierSubTitle",
            parent=styles["Normal"],
            fontSize=10,
            leading=15,
            textColor=colors.HexColor("#4A5568"),
            spaceAfter=18,
        )
        heading_style = ParagraphStyle(
            "DossierHeading",
            parent=styles["Heading2"],
            fontSize=14,
            leading=18,
            textColor=colors.HexColor("#2B6CB0"),
            spaceBefore=14,
            spaceAfter=10,
        )
        finding_style = ParagraphStyle(
            "FindingText",
            parent=styles["BodyText"],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#2D3748"),
            spaceAfter=4,
        )

        elements = []

        # Document Title Header
        elements.append(Paragraph("ThirdEye Threat Intelligence Dossier", title_style))
        elements.append(
            Paragraph(
                f"<b>Target Handle:</b> {target_handle}<br/>"
                f"<b>Generated At:</b> {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}<br/>"
                f"<b>Classification:</b> CONFIDENTIAL / FORENSIC EVIDENCE CORE",
                subtitle_style,
            )
        )
        elements.append(Spacer(1, 10))

        # Forensic Findings Section
        elements.append(Paragraph("Forensic Intelligence Findings", heading_style))

        if not findings:
            elements.append(
                Paragraph("<i>No specific forensic findings recorded for this target.</i>", finding_style)
            )
        else:
            list_items = [
                ListItem(
                    Paragraph(f"• {finding}", finding_style),
                    leftIndent=15,
                )
                for finding in findings
            ]
            elements.append(ListFlowable(list_items, bulletType="bullet"))

        elements.append(Spacer(1, 24))
        elements.append(
            Paragraph(
                "<i>This document is automatically generated by ThirdEye Forensic Intelligence Core v2.0-SIH.</i>",
                subtitle_style,
            )
        )

        doc.build(elements)
        return file_path
