"""Initial threat models

Revision ID: 27bc6a098e99
Revises: None
Create Date: 2026-09-22 15:51:01.815940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '27bc6a098e99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infrastructure_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('server_banner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infrastructure_nodes_ip_address'), 'infrastructure_nodes', ['ip_address'], unique=False)
    op.create_table('threat_actors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_actors_handle'), 'threat_actors', ['handle'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_actors_handle'), table_name='threat_actors')
    op.drop_table('threat_actors')
    op.drop_index(op.f('ix_infrastructure_nodes_ip_address'), table_name='infrastructure_nodes')
    op.drop_table('infrastructure_nodes')
    # ### end Alembic commands ###
