"""Pydantic schemas for extracted stylometric features, identifiers, and threat actor profiles."""
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field


class CryptoWallet(BaseModel):
    """Cryptocurrency wallet identifier."""

    model_config = ConfigDict(extra="ignore")

    currency: str = Field(..., description="Cryptocurrency symbol (BTC, XMR, ETH, etc.)")
    address: str = Field(..., description="Cryptocurrency public address")


class ExtractedIdentifiers(BaseModel):
    """Technical indicators and cryptographic identifiers harvested from text."""

    model_config = ConfigDict(extra="ignore")

    crypto_wallets: List[CryptoWallet] = Field(
        default_factory=list,
        description="List of extracted cryptocurrency wallet addresses with coin symbols",
    )
    pgp_keys: List[str] = Field(
        default_factory=list,
        description="PGP public key blocks, fingerprint hashes, or key IDs",
    )
    ip_addresses: List[str] = Field(
        default_factory=list,
        description="Extracted IPv4 or IPv6 network address indicators",
    )


class StylometricFeatures(BaseModel):
    """Classical stylometric markers and vector representations of authorship style."""

    model_config = ConfigDict(extra="ignore")

    # Lexical Features
    average_sentence_length: float = Field(
        default=0.0,
        ge=0.0,
        description="Mean sentence length in tokens/words",
    )
    average_word_length: float = Field(
        default=0.0,
        ge=0.0,
        description="Mean characters per word",
    )
    type_token_ratio: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Type-Token Ratio (unique words / total words)",
    )
    hapax_legomena_ratio: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Hapax Legomena Ratio (words occurring exactly once / total words)",
    )

    # Syntactic Features
    punctuation_frequency: Dict[str, int] = Field(
        default_factory=dict,
        description="Frequency count mapping for punctuation characters (!, ?, ..., etc.)",
    )
    pos_tag_distribution: Dict[str, float] = Field(
        default_factory=dict,
        description="Normalized distribution proportion of Part-of-Speech tags",
    )
    function_word_frequency: Dict[str, float] = Field(
        default_factory=dict,
        description="Frequency mapping for stopwords and function words",
    )

    # Structural Features
    paragraph_count: int = Field(
        default=1,
        ge=0,
        description="Count of distinct text paragraphs or line blocks",
    )
    uppercase_ratio: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Ratio of uppercase characters to total characters",
    )
    character_count: int = Field(
        default=0,
        ge=0,
        description="Total character length of the analyzed text",
    )

    # AI / Dense Semantic Vector
    embedding: List[float] = Field(
        default_factory=list,
        description="Dense vector embedding generated by Ollama for semantic stylometry",
    )


class ThreatActorProfile(BaseModel):
    """Unified threat actor profile aggregating stylometric fingerprint and technical identifiers."""

    model_config = ConfigDict(extra="ignore")

    handle: str = Field(..., description="Forum or marketplace author handle")
    platform: str = Field(..., description="Originating marketplace or forum name")
    features: StylometricFeatures = Field(
        default_factory=StylometricFeatures,
        description="Extracted stylometric fingerprint features",
    )
    identifiers: ExtractedIdentifiers = Field(
        default_factory=ExtractedIdentifiers,
        description="Extracted hard indicators (wallets, PGP, IPs)",
    )
    attribution_id: Optional[str] = Field(
        default=None,
        description="Resolved root ThreatActor cluster UUID or canonical identity",
    )
